# Generated by Django 4.0.6 on 2022-08-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('candidate_name', models.CharField(max_length=20)),
                ('party_name', models.CharField(max_length=20)),
                ('member_support', models.IntegerField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('candidate_photo', models.ImageField(upload_to='candidate_photo')),
                ('party_logo', models.ImageField(upload_to='party_logo')),
            ],
        ),
    ]
