# Generated by Django 3.2.15 on 2022-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateregister',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
