# Generated by Django 3.2.15 on 2022-08-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.IntegerField()),
                ('voter_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
