# Generated by Django 3.2.15 on 2022-08-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterregister',
            name='date',
            field=models.DateField(default='2000-12-02'),
        ),
    ]
