# Generated by Django 4.0.6 on 2022-08-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('voterid', models.IntegerField(max_length=10)),
                ('my_image', models.ImageField(upload_to='User')),
            ],
        ),
    ]
