# Generated by Django 4.0.6 on 2022-08-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='voterid',
            field=models.IntegerField(),
        ),
    ]
