# Generated by Django 4.0.6 on 2022-08-12 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoterApp', '0002_alter_userregister_voterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
