# Generated by Django 3.2.15 on 2022-10-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoterApp', '0002_auto_20220902_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
