# Generated by Django 3.2.15 on 2022-09-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VoterApp', '0004_delete_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=20)),
            ],
        ),
    ]
